# Generated by Django 2.2.2 on 2019-06-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Observable_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_in_this_account', models.CharField(max_length=30)),
                ('account_type_of_this_account', models.CharField(max_length=30)),
                ('email_address_of_this_account', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offender_name', models.CharField(max_length=30, unique=True)),
                ('email_address_of_offender', models.CharField(max_length=30)),
                ('observable_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Observable_Account')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toxic_percentage', models.FloatField(default=0)),
                ('severe_toxic_percentage', models.FloatField(default=0)),
                ('obscene_percentage', models.FloatField(default=0)),
                ('threat_percentage', models.FloatField(default=0)),
                ('insult_percentage', models.FloatField(default=0)),
                ('identity_hate_percentage', models.FloatField(default=0)),
                ('offender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Offender')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('email_address', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('accound_status', models.CharField(default='Active', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken_against_offender', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('prediction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Prediction')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Trusted_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Users')),
            ],
        ),
        migrations.AddField(
            model_name='offender',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Users'),
        ),
        migrations.AddField(
            model_name='observable_account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Users'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email_address', models.CharField(max_length=20)),
                ('time_and_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=64)),
                ('contents', models.CharField(max_length=500)),
                ('observable_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Observable_Account')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Users')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Authority')),
                ('message_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Message')),
                ('user_feedback_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.User_Feedback')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_world.Users')),
            ],
        ),
    ]
