# Generated by Django 2.2.3 on 2019-09-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_prediction_average_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='offender_id',
            field=models.FloatField(default=0),
        ),
    ]
